---
# tasks file for whirm.tribler_runner

# TODO: clean up the dependencies

- name: Installs Tribler dependencies
  action: apt pkg="{{item}}" state=present
  with_items:
    # - python-wxgtk2.8
    - libav-tools
    - libjs-excanvas
    - libjs-mootools
    - libsodium13
    - libstdc++6-4.8-dbg
    - libx11-6
    - python-cherrypy3
    - python-configobj
    - python-dbg
    - python-feedparser
    - python-leveldb
    - python-libtorrent
    - python-libtorrent-dbg
    - python-m2crypto
    - python-netifaces
    - python-networkx
    - python-pil
    - python-pip
    - python-pyasn1
    - python-requests
    - python-twisted
    - python-twisted-bin-dbg
    - python-virtualenv
    - python-zope.interface-dbg

- name: "Install plyvel on tribler user's $HOME"
  pip: name=plyvel extra_args="--user"
  remote_user: "{{tribler_user}}"
